---
# tasks file for ansible_podman_freeipa

- name: Install Dependencies
  import_tasks: "{{ role_path }}/tasks/install_dependencies.yml"
  tags:
    - setup-all

- name: Setup Rootless Podman
  import_tasks: "{{ role_path }}/tasks/setup_rootless_podman.yml"
  tags:
    - setup-all
    - setup-freeipa
    

- name: Setup Rootless Podman
  import_tasks: "{{ role_path }}/tasks/setup_freeipa.yml"
  tags:
    - setup-all
    - setup-freeipa

- name: Set Certbot script variable.
  set_fact:
    certbot_script: /usr/bin/certbot
