---

##
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/building_running_and_managing_containers/using-the-container-tools-api_using-the-container-tools-cli
#
##

## cannot clone: Operation not permitted
## user namespaces are not enabled in /proc/sys/kernel/unprivileged_userns_clone
## https://lwn.net/Articles/673597/
- name: Enable sysctl kernel.unprivileged_userns_clone
  ansible.posix.sysctl:
    name: kernel.unprivileged_userns_clone
    value: '1'
    sysctl_set: true
    state: present
    sysctl_file: /etc/sysctl.d/00_local_userns.conf
    reload: true
  become: true
  when: ansible_os_family == 'Debian'

- name: Enable sysctl rootless config
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    sysctl_file: /etc/sysctl.d/01_rootless.conf
    reload: true
  with_items:
    - {name: 'net.ipv4.ip_unprivileged_port_start', value: '80'}
    - {name: 'net.ipv4.ping_group_range', value: '0 2000000'}
  become: true

- name: Set up storage.conf
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "/etc/containers/{{ item }}"
    mode: 0644
  with_items:
    - "storage.conf"
  become: true
