---
# handlers file for ansible_podman_freeipa

- name: enable podman-rootless-socket
  ansible.builtin.systemd:
    name: freeipa-rootless-podman.socket
    enabled: true
    daemon_reload: true
  become: true

- name: enable freeipa-server
  ansible.builtin.systemd:
    name: freeipa.service
    enabled: true
    daemon_reload: true
  become: true
